export const searchActionTypes = {
  CHANGE_SEARCH_INPUT_VALUE: "CHANGE_SEARCH_INPUT_VALUE",
  CLEAR_SEARCH_INPUT_VALUE: "CLEAR_SEARCH_INPUT_VALUE",
  SEARCH_MOVIES_RESULTS: "SEARCH_MOVIES_RESULTS",
};
