export const genresActionTypes = {
  FETCH_GENRES_RESULTS_REQUEST: 'FETCH_GENRES_RESULTS_REQUEST',
  FETCH_GENRES_RESULTS_SUCCESS: 'FETCH_GENRES_RESULTS_SUCCESS',
  FETCH_GENRES_RESULTS_FAILURE: 'FETCH_GENRES_RESULTS_FAILURE',
  FETCH_SINGLE_GENRE: 'FETCH_SINGLE_GENRE',
};
