export const moviesActionTypes = {
  FETCH_MOVIES_RESULTS_REQUEST: "FETCH_MOVIES_RESULTS_REQUEST",
  FETCH_MOVIES_RESULTS_SUCCESS: "FETCH_MOVIES_RESULTS_SUCCESS",
  FETCH_MOVIES_RESULTS_FAILURE: "FETCH_MOVIES_RESULTS_FAILURE",
  FETCH_SINGLE_MOVIE: "FETCH_SINGLE_MOVIE",
};
