export const moviesActionTypes = {
  FETCH_MOVIES_RESULTS_REQUEST: "FETCH_MOVIES_RESULTS_REQUEST",
  FETCH_MOVIES_RESULTS_SUCCESS: "FETCH_MOVIES_RESULTS_SUCCESS",
  FETCH_MOVIES_RESULTS_FAILURE: "FETCH_MOVIES_RESULTS_FAILURE",
  FETCH_SINGLE_MOVIE: "FETCH_SINGLE_MOVIE",
  SAVE_HERO_MOVIE: "SAVE_HERO_MOVIE",

  FETCH_MOVIE_DETAILS: "FETCH_MOVIE_DETAILS",
  MOVIE_INFO_MODAL_OPEN: "MOVIE_INFO_MODAL_OPEN",
  MOVIE_INFO_MODAL_CLOSE: "MOVIE_INFO_MODAL_CLOSE",
  SOUND_MUTE_ON: "SOUND_MUTE_ON",
  SOUND_MUTE_OFF: "SOUND_MUTE_OFF",
};
